### ISSUE TITLE
"failed to parse json, invalid cahracter <" --  (probably a 404 page)

### ISSUE THREAD

**Issue by NullVoxPopuli** [bakingbacon/bakinbacon#13]
**Describe the bug**
I launched the app via the terminal so I could look at longs while bakinbakcon was running, I get a lot of:
```
ERRO[2021-12-23T20:38:12-05:00] Unable to get /head; Will try again           Endpoint="http://mainnet-eu.rpc.bakinbacon.io" error="failed to get block 'head': failed to parse json: invalid character '<' looking for beginning of value"
```
and I think it's preventing me from getting passed step 2, setup ledger device (I have Nano S (I learned that the Nano X doesn't work)).

**To Reproduce**
1. Be on Ubuntu 21.10
2. Launch app via `/bakinbacon-linux-amd64  -webuiaddr 127.0.0.1 -webuiport 8082`
3. observe errors

**Expected behavior**
no errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: ubuntu 21.10
 - Browser n/a
 - Version 1.1.0

**Additional context**
Trying to learn how to bake on the testnet -- been curious how it all works, and there is a faucet to help testnet folks get enough tez

**Comment by NullVoxPopuli** [comment]
tried again today, got a invalid memory address error:
```
021/12/24 15:22:18 http: panic serving 127.0.0.1:49824: runtime error: invalid memory address or nil pointer dereference
goroutine 86 [running]:
net/http.(*conn).serve.func1(0xc0002d0640)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:1805 +0x153
panic(0x91f8a0, 0x1022210)
	/opt/hostedtoolcache/go/1.16.11/x64/src/runtime/panic.go:971 +0x499
bakinbacon/storage.(*Storage).SaveLedgerToDB(0x0, 0xc00002a1b0, 0x24, 0xc0003e87c0, 0x10, 0x2, 0x0, 0xc0003e875a)
	/home/runner/work/bakinbacon/bakinbacon/storage/config.go:142 +0x7c
bakinbacon/baconsigner.(*LedgerSigner).ConfirmBakingPkh(0xc0002e4be0, 0xc0000ca4e0, 0x24, 0xc0003e87c0, 0x10, 0xc0003f06c8, 0xc00050c2c0)
	/home/runner/work/bakinbacon/bakinbacon/baconsigner/ledger.go:254 +0x785
bakinbacon/baconsigner.(*BaconSigner).ConfirmBakingPkh(0xc0002e4800, 0xc0000ca4e0, 0x24, 0xc0003e87c0, 0x10, 0x414a58, 0x90)
	/home/runner/work/bakinbacon/bakinbacon/baconsigner/baconsigner.go:104 +0x59
bakinbacon/webserver.(*WebServer).confirmBakingPkh(0xc0004884e0, 0xdd2330, 0xc0001dc2a0, 0xc000690300)
	/home/runner/work/bakinbacon/bakinbacon/webserver/api_wizard.go:45 +0x21d
net/http.HandlerFunc.ServeHTTP(0xc00022cb00, 0xdd2330, 0xc0001dc2a0, 0xc000690300)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:2050 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000228000, 0xdd2330, 0xc0001dc2a0, 0xc000690000)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000152090, 0xdd2330, 0xc0001dc2a0, 0xc000690000)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8
net/http.serverHandler.ServeHTTP(0xc0001dc1c0, 0xdd2330, 0xc0001dc2a0, 0xc000690000)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0002d0640, 0xdd3900, 0xc0000b8080)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.16.11
```

**Comment by NullVoxPopuli** [comment]
I think these two issues are unrelated.

For the original issue, deleting the .db file resolves.

**Comment by utdrmac** [comment]
Ok. Please open an issue for the panic. I found the reason for it and am working on a fix.

**Comment by NullVoxPopuli** [comment]
oh legit! https://github.com/bakingbacon/bakinbacon/issues/14
