### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by NullVoxPopuli** [bakingbacon/bakinbacon#14]
**Describe the bug**
When attempting to Setup my Ledger device (step  2), I get an invalid memory address error after I "Accept" on the ledger

**To Reproduce**
1. `./bakinbacon-linux-amd64 -webuiaddr 127.0.0.1 -webuiport 8082 -network hangzhounet`
2. http://localhost:8082/
3. Click "Ledger Wallet"
4. Click "Test Ledger" -- See `Detected ledger: Baking 2.2.13`
5. Click "Continue"
6. Click "Confirm Address"
7. Observe error in the terminal:
```
NFO[2021-12-24T22:44:20-05:00] New Block                                     ChainID=NetXZSsxBpMQeAT Cycle=60 Hash=BMefeUVjmoVuisPpExo6mfdRZUXepQrWSS63uQDAY8DRMzygzx2 Level=246576
INFO[2021-12-24T22:44:20-05:00] Notification last sent within 10 minutes     
ERRO[2021-12-24T22:44:20-05:00] Checking signer status                        error="Loading Delegate: No delegate key defined"
2021/12/24 22:44:21 http: panic serving 127.0.0.1:59626: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
net/http.(*conn).serve.func1(0xc0000ec0a0)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:1805 +0x153
panic(0x91f8a0, 0x1022210)
	/opt/hostedtoolcache/go/1.16.11/x64/src/runtime/panic.go:971 +0x499
bakinbacon/storage.(*Storage).SaveLedgerToDB(0x0, 0xc00062f290, 0x24, 0xc000539570, 0x10, 0x2, 0x0, 0xc000539582)
	/home/runner/work/bakinbacon/bakinbacon/storage/config.go:142 +0x7c
bakinbacon/baconsigner.(*LedgerSigner).ConfirmBakingPkh(0xc0000cc180, 0xc00002a450, 0x24, 0xc000539570, 0x10, 0xc0000dc6c8, 0xc0001766e0)
	/home/runner/work/bakinbacon/bakinbacon/baconsigner/ledger.go:254 +0x785
bakinbacon/baconsigner.(*BaconSigner).ConfirmBakingPkh(0xc0002f4800, 0xc00002a450, 0x24, 0xc000539570, 0x10, 0x414a58, 0x90)
	/home/runner/work/bakinbacon/bakinbacon/baconsigner/baconsigner.go:104 +0x59
bakinbacon/webserver.(*WebServer).confirmBakingPkh(0xc0001080c0, 0xdd2330, 0xc0004762a0, 0xc000468400)
	/home/runner/work/bakinbacon/bakinbacon/webserver/api_wizard.go:45 +0x21d
net/http.HandlerFunc.ServeHTTP(0xc000066790, 0xdd2330, 0xc0004762a0, 0xc000468400)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:2050 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000238000, 0xdd2330, 0xc0004762a0, 0xc000468200)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc00018c000, 0xdd2330, 0xc0004762a0, 0xc000468200)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8
net/http.serverHandler.ServeHTTP(0xc0003f00e0, 0xdd2330, 0xc0004762a0, 0xc000468200)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0000ec0a0, 0xdd3900, 0xc0003ea380)
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.16.11/x64/src/net/http/server.go:2994 +0x39b
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by utdrmac** [comment]
v1.1.1 should be building. look for this in the releases section in about 5-10m.

**Comment by NullVoxPopuli** [comment]
success! thanks!
